sudo: false
language: node_js
node_js:
  - "12.13"
branches:
  only:
    - master
install:
  - npm install
script:
  - npm test
  - npm build
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
